apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofka-segimiento-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofka-segimiento
  template:
    metadata:
      labels:
        app: sofka-segimiento
    spec:
      containers:
      - name: sofka-segimiento
        image: rcarvajalf/sofkatracingapi:0.0.2
        ports:
        - containerPort: 8081
        env:
        - name: HOSTDB
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: HOSTDB
        - name: PORTDB
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: PORTDB
        - name: DBNAMEMONITOR
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: DBNAMEMONITOR
        - name: RABBITURL
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: RABBITURL
        - name: PORTAPPSOFKAMONITOR
          valueFrom:
            configMapKeyRef:
              name: service-conf
              key: PORTAPPSOFKAMONITOR

---
apiVersion: v1
kind: Service
metadata:
  name: sofka-segimiento-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001    
  selector:            
    app: sofka-segimiento